name: "RELEASE"

on:
  # Triggered manually by user action
  workflow_dispatch:
    inputs:
      # The SemVer tag that will be used for the docker image and the release
      tag:
        description: "The Docker image + release tag"
        required: true
        default: "0.0.0"

jobs:
  SETUP:
    name: SETUP ENV
    runs-on: ubuntu-latest
    steps:
        # Checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v3

        # If the env doesn't match the branch, the action failed and stop; else, continue
      - name: 2 - CHECK VARIABLES TO MATCH ENVIRONMENT
        if: github.ref != 'refs/heads/main'
        run: exit 1

  BUILD:
    name: BUILD
    needs: [SETUP-ENV]
    runs-on: ubuntu-latest
    steps:
        # Checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v3

        # Login to container registry
      - name: 2 - LOGIN TO GHCR.IO
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Setup variable for Docker tag
      - name: 3 - SETUP ENV VARS
        run: |
          echo "SHA=$(echo $GITHUB_SHA | head -c8)" >> $GITHUB_ENV
          echo "DATE=$(date +%Y%m%d%H%M)"           >> $GITHUB_ENV
          echo "BRANCH=$GITHUB_REF_NAME"            >> $GITHUB_ENV

        # Build and push the app with given file and tag
      - name: 4 - BUILD + PUSH
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: build/package/go-eland/Dockerfile
          tags: |
            ghcr.io/blyndusk/go-eland:${{ env.BRANCH }}-${{ env.SHA }}-${{ env.DATE }}
            ghcr.io/blyndusk/go-eland:${{ env.BRANCH }}-${{ env.SHA }}
            ghcr.io/blyndusk/go-eland:${{ github.event.inputs.tag }}

        # Output the logs
      - name: 5 - IMAGE DIGEST
        run: echo ${{ steps.docker_build.outputs.digest }}

  RELEASE:
    name: RELEASE
    needs: [BUILD]
    runs-on: ubuntu-latest
    steps:
      # checkout to current workspace
      - name: 1 - CHECKOUT
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

        # generate changelogs from the closed issues
      - name: 2 - CHANGELOG
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        id: changelog_id
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: true
          enhancementLabels: "feat"
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          stripGeneratorNotice: true
          verbose: true

      # create release according to tag input
      - name: 3 - CREATE RELEASE
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: v${{ github.event.inputs.tag }}
          body: ${{ steps.changelog_id.outputs.changelog }}
          draft: false
          prerelease: false
